spring:
  profiles.active: dev
  application:
    name: ${SERVICE:hand-equity-service}
server:
  port: ${PORT:9234}
  error:
    include-message: always
---
spring:
  profiles: prod
eureka:
  client.serviceUrl.defaultZone: ${DISCOVERY_URI:http://discovery-service:8761/eureka}
